### ISSUE TITLE
Error on m62_m65_exec function

### ISSUE THREAD

**Issue by Yuri-Santiago** [Paciente8159/uCNC-modules#79]
The function m62_m65_exec is expecting a group extended between 62 and 65, but the correct number has to be the macro M62 and M65, without this the M62 to M64 commands throws error number 20 (STATUS_GCODE_UNSUPPORTED_COMMAND).
![image](https://github.com/user-attachments/assets/1913e30d-e5af-4218-a868-c6fc4491d0f5)
With this code it woks fine.

**Comment by Paciente8159** [comment]
Thanks for reporting this
